# Sensitive configuration - DO NOT commit this file
spring.datasource.username=postgres
spring.datasource.password=admin

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookieName=explorer

spring.app.OPENROUTER_API_KEY=your-openrouter-api-key-here
